export enum ContactType {
  MOH_AGENCIES = 'MOH_AGENCIES',
  REGIONAL_HEALTH_BUREAU = 'REGIONAL_HEALTH_BUREAU',
  FEDERAL_HOSPITALS = 'FEDERAL_HOSPITALS',
  ADDIS_ABABA_HOSPITALS = 'ADDIS_ABABA_HOSPITALS',
  UNIVERSITY_HOSPITALS = 'UNIVERSITY_HOSPITALS',
  ASSOCIATIONS = 'ASSOCIATIONS',
  PARTNERS = 'PARTNERS',
}

export enum ContactPosition {
  HEAD = 'HEAD',
  DEPUTY_HEAD = 'DEPUTY_HEAD',
  MEDICAL_SERVICE_LEAD = 'MEDICAL_SERVICE_LEAD',
  CHIEF_EXECUTIVE_DIRECTOR = 'CHIEF_EXECUTIVE_DIRECTOR',
  MEDICAL_DIRECTOR = 'MEDICAL_DIRECTOR',
  CEO = 'CEO',
  OTHER = 'OTHER',
}
